import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from "react";
import {FetchFunctionsBNB, FetchFunctionsBTC, FetchFunctionsETH} from "../functions/fetchFunctions";

export default function Home() {
    const url = 'https://blockchain.info/ticker'
    const urlCrypto = "https://api.coingecko.com/api/v3/exchange_rates"
    const [bitcoin, setBitcoin] = useState(0)
    const [eth, setEth] = useState(0)
    const [binance, setBinance] = useState(0)

    useEffect(() => {
        FetchFunctionsBTC(url, setBitcoin)
        FetchFunctionsETH(urlCrypto, setEth)
        FetchFunctionsBNB(urlCrypto, setBinance)
        }, [])

const handleRefresh = () => {
    FetchFunctionsBTC(url, setBitcoin)
    FetchFunctionsETH(urlCrypto, setEth)
    FetchFunctionsBNB(urlCrypto, setBinance)
    console.log("Ça refresh ma gueule !")
}

    return (
        <div className={styles.container}>
            <Head>
                <title>Little Crypto Watcher</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="main">
                <h1 style={{marginBottom: "10px"}}>BITCOIN</h1>
                <h2 className={styles.currencyDisplayBTC}>{bitcoin.toLocaleString("fr-FR")}€</h2>

                <h1 style={{marginBottom: "10px"}}>BINANCE</h1>
                <h2 className={styles.currencyDisplay}>{(bitcoin / binance).toLocaleString("fr-FR")}€</h2>
                <span>(soit {binance.toFixed(2)} BINANCE = 1x BITCOIN)</span>

                <h1 style={{marginBottom: "10px"}}>ETHEREUM</h1>
                <h2 className={styles.currencyDisplay}>{(bitcoin / eth).toLocaleString("fr-FR")}€</h2>
                <span>(soit {eth.toFixed(2)} ETHEREUM = 1x BITCOIN)</span>
            </div>
            <div className={styles.refresh}>
                <button onClick={handleRefresh}>Refresh</button>
            </div>
        </div>
    )
}
