import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, {useEffect, useState} from "react";
import {FetchFunctionsBNB, FetchFunctionsBTC, FetchFunctionsETH} from "../functions/fetchFunctions";
import {bitcoinLogo, ethLogo, binanceLogo} from "../assets/svg/svgLogos"

export default function Home() {
    const url = 'https://blockchain.info/ticker'
    const urlCrypto = "https://api.coingecko.com/api/v3/exchange_rates"
    const [bitcoin, setBitcoin] = useState(0)
    const [eth, setEth] = useState(0)
    const [binance, setBinance] = useState(0)


    useEffect(() => {
        FetchFunctionsBTC(url, setBitcoin)
        FetchFunctionsETH(urlCrypto, setEth)
        FetchFunctionsBNB(urlCrypto, setBinance)
        window.addEventListener("load",function() {
            setTimeout(function(){
                window.scrollTo(0, 1);
            }, 0);
        });
    }, [])

    const handleRefresh = () => {
        FetchFunctionsBTC(url, setBitcoin)
        FetchFunctionsETH(urlCrypto, setEth)
        FetchFunctionsBNB(urlCrypto, setBinance)
        console.log("Ça refresh ma gueule !")
    }



    return (
        <div className={styles.container}>
            <Head>
                <title>Little Crypto Watcher</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="apple-touch-icon" href="%PUBLIC_URL%/apple-touch-icon.png"/>
                <link rel="apple-touch-icon" href="%PUBLIC_URL%/apple-touch-icon.png"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1 className={styles.pageTitle}>Live Rates</h1>
            <div className="main">
                <div className={styles.liveRateItem} style={{backgroundColor: "#DEF7F5"}}>
                    <h1>{bitcoinLogo} BITCOIN</h1>
                    <h2 className={styles.currencyDisplayBTC}>{bitcoin.toLocaleString("fr-FR")}€</h2>
                </div>

                <div className={styles.liveRateItem} style={{backgroundColor: "#FDEDF3"}}>
                    <h1>{binanceLogo} BINANCE</h1>
                    <h2 className={styles.currencyDisplayBinance}>{(bitcoin / binance).toLocaleString("fr-FR")}€</h2>
                    <span>(soit {binance.toFixed(2)} BINANCE = 1x BITCOIN)</span>
                </div>

                <div className={styles.liveRateItem} style={{backgroundColor: "#EBF4FF"}}>
                    <h1>{ethLogo} ETHEREUM</h1>
                    <h2 className={styles.currencyDisplay}>{(bitcoin / eth).toLocaleString("fr-FR")}€</h2>
                    <span>(soit {eth.toFixed(2)} ETHEREUM = 1x BITCOIN)</span>
                </div>
            </div>
            <div className={styles.refresh}>
                <button onClick={handleRefresh}>Refresh</button>
            </div>
        </div>
    )
}
